-- MySQL Script generated by MySQL Workbench
-- Sun Sep 30 10:57:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema timesheet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema timesheet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `timesheet` DEFAULT CHARACTER SET utf8mb4;
USE `timesheet` ;

-- -----------------------------------------------------
-- Table `timesheet`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`perfil` (
  `perfil_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `criado_por` VARCHAR(100) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_por` VARCHAR(100) NOT NULL,
  `data_ultima_atualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`perfil_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesheet`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(12) NULL,
  `email` VARCHAR(100) NOT NULL,
  `perfil_id` INT NOT NULL,
  `valor_hora` FLOAT(10,2) NULL,
  `timezone` VARCHAR(5) NOT NULL,
  `criado_por` VARCHAR(100) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `atualizado_por` VARCHAR(100) NOT NULL,
  `data_ultima_atualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_usuario_perfil_idx` (`perfil_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `timesheet`.`perfil` (`perfil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesheet`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`cliente` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `criado_por` VARCHAR(100) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `atualizado_por` VARCHAR(100) NOT NULL,
  `data_ultima_atualizacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesheet`.`squad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`squad` (
  `squad_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `administrador_id` INT NOT NULL,
  `criado_por` VARCHAR(100) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `atualizado_por` VARCHAR(100) NOT NULL,
  `data_ultima_atualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`squad_id`),
  INDEX `fk_Squad_usuario1_idx` (`administrador_id` ASC) VISIBLE,
  CONSTRAINT `fk_Squad_usuario1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `timesheet`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesheet`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`projeto` (
  `projeto_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cliente_id` INT NOT NULL,
  `squad_id` INT NULL,
  `criado_por` VARCHAR(100) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `atualizado_por` VARCHAR(100) NOT NULL,
  `data_ultima_atualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`projeto_id`),
  INDEX `fk_Projeto_Cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_projeto_squad1_idx` (`squad_id` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `timesheet`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_squad1`
    FOREIGN KEY (`squad_id`)
    REFERENCES `timesheet`.`squad` (`squad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesheet`.`membros_squad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`membros_squad` (
  `membros_squad_id` INT NOT NULL AUTO_INCREMENT,
  `squad_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `criado_por` VARCHAR(100) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `atualizado_por` VARCHAR(100) NOT NULL,
  `data_ultima_atualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`membros_squad_id`),
  INDEX `fk_membros_squad_Squad1_idx` (`squad_id` ASC) VISIBLE,
  INDEX `fk_membros_squad_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_membros_squad_Squad1`
    FOREIGN KEY (`squad_id`)
    REFERENCES `timesheet`.`squad` (`squad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membros_squad_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `timesheet`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesheet`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` BLOB(5000) NULL,
  `criado_por` VARCHAR(100) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `atualizado_por` VARCHAR(100) NOT NULL,
  `data_ultima_atualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesheet`.`lancamento_horas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`lancamento_horas` (
  `lancamento_horas_id` INT NOT NULL AUTO_INCREMENT,
  `projeto_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NULL,
  `descricao` BLOB(5000) NULL,
  `criado_por` VARCHAR(100) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `atualizado_por` VARCHAR(100) NOT NULL,
  `data_ultima_atualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`lancamento_horas_id`),
  INDEX `fk_lancamento_horas_projeto1_idx` (`projeto_id` ASC) VISIBLE,
  INDEX `fk_lancamento_horas_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_lancamento_horas_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_lancamento_horas_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_lancamento_horas_projeto1`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `timesheet`.`projeto` (`projeto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_horas_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `timesheet`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_horas_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `timesheet`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_horas_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `timesheet`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
